# Change these first
owner: Sup3rFire # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Personal Website
    url: https://superfi.re
  - name: Personal Website (Backup Domain)
    url: https://sf-hub.cc

status-website:
  theme: dark
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.superfi.re
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/Sup3rFire/Sup3rFire/main/pages/img/owo.png
  name: SuperFire Status
  introTitle: "The uptime status of (almost) all the things I've created."
  introMessage: Welcome to the uptime status of everything I have created in the past (excluding things that don't have an accessible web API)
  navbar:
    - title: Home
      href: https://superfi.re
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
